version: '3'
services:
  gridmeter:
    build: .
    image: gridmeter
    entrypoint: gridmeter
    volumes:
      - .:/app
      - /tmp:/tmp
    env_file:
      - dev-env.env

  test:
    image: gridmeter
    entrypoint: py.test
    volumes:
      - .:/app

  blacken:
    image: gridmeter
    entrypoint: black .
    volumes:
      - .:/app

  docs:
    image: gridmeter
    ports:
      - "${HOST_PORT_DOCS:-8000}:8000"
    entrypoint: make -C docs livehtml
    volumes:
      - .:/app

  fury:
    image: gridmeter
    entrypoint: python setup.py sdist upload -r fury
    volumes:
      - .:/app

  jupyter:
    image: gridmeter
    entrypoint: jupyter lab scripts/ --port=$JUPYTER_PORT --no-browser --ip=0.0.0.0 --allow-root
    env_file:
      - dev-env.env
    volumes: 
      - .:/app 
    ports: 
      - "${JUPYTER_PORT:-8123}:${JUPYTER_PORT:-8123}"
